---
name: Release

on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
    - completed

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  release:
    uses: sprsaas/reusable-workflows/.github/workflows/reusable-release.yml@main
    secrets:
      SEMANTIC_RELEASE_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
