---
on:
  workflow_call:
    secrets:
      KUBE_CONFIG:
        description: Kubeconfig file provided as input to the action
        required: true

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - name: Setup environment
      uses: sprsaas/reusable-workflows/actions/helm-setup@main
      with:
        kubectl-version: "v1.23.0"
        helm-version: "v3.10.1"

    - name: Login in Kubernetes
      uses: azure/k8s-set-context@v3
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
