---
name: Release

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git branch reference
        type: string
        required: true
        default: main
    secrets:
      SEMANTIC_RELEASE_TOKEN:
        description: GitHub token for semantic release
        required: true

jobs:
  release:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: "lts/*"

    - name: Copy rules
      run: |
        cp .github/config/.releaserc.json .

    - name: Install semantic release
      run: |
        npm install -g semantic-release@22 \
          @semantic-release/git @semantic-release/github \
          @semantic-release/exec @semantic-release/error @semantic-release/changelog \
          @semantic-release/commit-analyzer @semantic-release/release-notes-generator \
          @commitlint/cli conventional-changelog-conventionalcommits

    - name: Release
      run: npx semantic-release --no-ci
      env:
        GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
