---
name: Reusable-Quality

on:
  workflow_call:
    inputs:
      continue-on-error:
        type: boolean
        description: "Enable continue-on-error option"
        required: false
        default: true

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Lint actions and workflows
      uses: sprsaas/reusable-workflows/actions/action-lint@main

    - name: Commit Lint
      uses: wagoid/commitlint-github-action@v5
      continue-on-error: ${{ inputs.continue-on-error }}

    - name: Dockerfile Lint
      uses: hadolint/hadolint-action@v3.1.0
      if: ${{ hashFiles('Dockerfile') != '' }}
      continue-on-error: ${{ inputs.continue-on-error }}
      with:
        config: .github/config/.hadolint.yml
        dockerfile: Dockerfile

  secret-detection:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Run Gitleaks
      id: gitleaks
      uses: DariuszPorowski/github-action-gitleaks@v2
      with:
        verbose: true

    - name: Upload Gitleaks JSON report to artifacts
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: gitleaks
        path: ${{ steps.gitleaks.outputs.report }}
